from pathlib import Path
import fitz
from unittest import TestCase
from app.ai.util.ai_job_posting_utils import is_job_relevant
from app.util.parse_pdf import parse_pdf_to_text

current_script_path = Path(__file__).parent.parent.parent
resources_path = current_script_path / 'resources' / 'test_resume.pdf'
resume_path = resources_path.resolve()

invalid_job_description = "We are looking for a Firmware Engineer for a direct Manufacturing client. Job Title: Firmware Engineer Location: San Diego CA. Type - Fulltime direct hire. Our client is in search of a Software Engineer with a versatile skill set to play a crucial role in the development and enhancement of embedded firmware, test software, and PC software for our hardware product line and sensors. We are a well-established company located in San Diego, and we are seeking a candidate with strong technical proficiency, including expertise in the C language, who can adapt to various responsibilities within our dynamic and close-knit work environment. Responsibilities: Embedded Firmware/Product Development: Contribute to the creation of new firmware or improve existing firmware for our current hardware product line and sensors. Test Software Development: Utilize LabVIEW or similar tools to craft effective test scripts for software testing, ensuring comprehensive coverage for hardware product testing. PC Software for Data in Use: Develop and maintain PC software for product testing and interfacing, including integration with ERP systems. Programming Languages: Apply expertise in the C language for software development. Familiarity with assembly (ASSY) language is advantageous. Some experience in Python and LabVIEW is a plus. ERP Knowledge: Familiarity with ERP systems, such as Oracle, SAP, or homegrown systems. Leadership and Mentoring: Assume a senior role and provide mentorship to team members. Collaborate effectively in a small group and embody a \"Jack of All Trades\" mindset. Communication Skills: Demonstrate excellent interpersonal skills to navigate effectively across different levels in a small company environment. Engage with customers as necessary. Adaptability: Thrive in a fast-paced and evolving product development environment. Embrace flexibility and openness to shifting priorities. Industry Experience: Preferred industry experience in aerospace, aircraft, automotive, military vehicles, or related fields. Consideration given to candidates from other industries based on overall experience and adaptability. Long-Term Commitment: Exhibit the ability to make a sustained commitment to personal growth, career development, company success, and industry excellence. Experience and Education: Possess 5-10+ years of experience in software engineering. A bachelor's degree in Computer Science (BSCS) is expected. A master's degree in Computer Science (MSCS) is a valuable asset."
valid_job_description = "Location: Remote | Must sit in ID, OR, WA, CA, UT, AZ, NV , CO Employment Type: 12-month contract to hire  Pay Range: $55-65 / hr Benefits: Medical insurance, 401K, sick leave, and employee assistance program. Depending on your package selection, Averro offers PTO, paid holidays, dental/vision, pet, and legal insurance. Role & Responsibilities: We are currently seeking a talented and experienced Software QA Engineer to join our team! This is an excellent opportunity for individuals with 3-5 years of experience in QA testing, particularly those who excel in creating test plans using Azure DevOps (ADO) and possess proficiency in automation tools such as Selenium and/or Pytest. The successful candidate will contribute to the advancement of their career in the dynamic field of software quality assurance.  Key Responsibilities:  Develop and execute comprehensive test plans in Azure DevOps (ADO). Utilize automation tools, specifically Selenium and/or Pytest, to enhance testing efficiency. Conduct Python scripting to automate test scenarios and improve testing processes. Collaborate with cross-functional teams to ensure the delivery of high-quality software products. Integrate continuous integration tools such as Jenkins/ADO and GIT into the testing process. Essential Qualifications:  3-5 years of experience in software quality assurance and testing. Proven expertise in creating and implementing test plans using Azure DevOps (ADO). Hands-on experience with automation tools, specifically Selenium and/or Pytest. Proficiency in Python scripting for test automation. Familiarity with continuous integration tools like Jenkins/ADO and GIT. Bonus Qualifications:  Additional experience with other automation tools or programming languages. Certification in software testing (e.g., ISTQB). WHY AVERRO? Averro is a Veteran-Owned organization dedicated to delivering innovative talent solutions and technology services. Our commitment to values like curiosity, trust-building, and empowerment reflects in our client satisfaction, timely support, and unmatched consultant care. Join us on a journey of professional growth, where your skills and contributions are valued.  Averro is an equal opportunity employer, fostering diversity, equity, and inclusion. All qualified applicants will be considered for employment, irrespective of backgrounds, consistent with legal obligations. We celebrate the unique perspectives each team member brings, contributing to an inclusive workplace. Your career ascent begins with Averro!"
doc = fitz.open()
resume_text = parse_pdf_to_text(resume_path)


class AiJobPostingUtilsTest(TestCase):

    def test_job_is_relevant(self):
        self.assertTrue(is_job_relevant(valid_job_description, resume_text))

    def test_job_not_relevant(self):
        self.assertFalse(is_job_relevant(invalid_job_description, resume_text))
